### PR TITLE
cli: add option to choose color manually

### PR DESCRIPTION
**Pull request by pleshevskiy**
I'm currently working on a full integration with `fzf` and himalaya auto-detects `FZF_DEFAULT_COMMAND` and `--preview` as no tty. It would be great if these changes could be merged.

### CODE REVIEW

**Comment by pleshevskiy** [comment]
I also fixed the tests, cause someone broke it :)

**Comment by soywod** [comment]
Thanks a lot for your contribution :slightly_smiling_face: the v0.6 should come very soon (within few days) with big structural and API changes, I come back to you whenever the `development` branch is up-to-date!

**Comment by soywod** [comment]
I just released the [v0.6.0](https://github.com/soywod/himalaya/releases/tag/v0.6.0), which includes the code splitting. Sorry for the conflicts! But they should be easy to fix, everything move down a level (there is no more `cli` folder). Let me know if you need help. Once the conflicts resolved we will be able to merge your PR :slightly_smiling_face:

**Comment by pleshevskiy** [comment]
Thanks! I don't have time, sorry

**Comment by soywod** [comment]
I was not able to push directly on your fork, so I pushed your changes directly on `develop`. Thanks a lot for your contribution and sorry for the delay! I should be available in the next release #433.

**Pull request closed without merging**
