### PR TITLE
TUI

### PR DESCRIPTION
**Pull request by TornaxO7**
You can view in this pull request the "process" of the implementation of the TUI. Pls consider that I'm completely new in rust so I might be pretty slow, but I'll do my best.

# Status
Created the `src/tui` directory with

```bash
cargo new --lib tui
```

# Information for maintainer (@soywod )
I'm creating the pull request now, so you can review any time the latest commits whenever you want, so you can give me immediately a feedback if something doesn't suit you. Is that fine for you?

### CODE REVIEW

**Comment by soywod** [comment]
I converted the PR as draft. Thanks for the initiative!

**Comment by TornaxO7** [comment]
# Status
At the moment it looks like this, when running `himalaya tui`:

Screenshot

# Note
I have a suggestion for the `run()` funtion in `src/main`:

1. Should we rather create an extra function which reads the config information
of the `config.toml` file? Because I'm thinking of giving the user the
possibility to reload the config anytime if the TUI is enabled.

2. A little rewrite of the matching part. I wrote my suggestion in the `src/main.rs`
   file. You can find by searching the word `SUGGESTION` in it.

**Comment by TornaxO7** [comment]
https://github.com/TornaxO7/himalaya/projects/1

So I created the project here, if you want to see the process.

**Comment by soywod** [comment]
> 1. Should we rather create an extra function which reads the config information
> of the `config.toml` file? Because I'm thinking of giving the user the
> possibility to reload the config anytime if the TUI is enabled.

A refactor of msg matching args has already been proposed and merged, you can check it for inspiration https://github.com/soywod/himalaya/pull/151

> 2. A little rewrite of the matching part. I wrote my suggestion in the `src/main.rs`
>    file. You can find by searching the word `SUGGESTION` in it.

It could be related to #156. I planned to implement a daemon that keep in memory the login process. I think it could be the right place to reevaluate the config.

**Comment by TornaxO7** [comment]
@soywod 
# Question
What do you think about enabling a second config file called `tui.toml`? Because I see that there will be many ways to configure it starting from the looking of the borders and colors until the customizable keybindings.

**Comment by soywod** [comment]
What is preventing the fact to put new TUI options inside the existing one ? They could be attach to a new category, or prefixed with `tui-`. Those options could be also defined as feature !

**Comment by TornaxO7** [comment]
I thought that it this section than might be too big, but yeah.... I guess you're right.

**Comment by TornaxO7** [comment]
By the way, congratulations for > 1.000 stars on github for himalaya :)

**Comment by TornaxO7** [comment]
# Question
I'm a little bit unsure what to do with the attributes of the mailboxes:

image

Do we need to display them?

**Comment by TornaxO7** [comment]
# Question
Since I'll add a new part to the Config, should I split up the `src/config/model.rs` into it's different structs? Like
```
src/config/
    account.rs
    config.rs
    tui.rs
```
? What do you think about that? From my point of view, this makes it clearer, where to find what.

**Comment by TornaxO7** [comment]
# Question
In your `src/config/model.rs` you have this macro:

```rust
    #[serde(flatten)]
    pub accounts: HashMap<String, Account>,
```

How does this work? I can't find it, if I search the term `flatten` in its [doc](https://docs.serde.rs/serde/index.html?search=flatten).

**Comment by TornaxO7** [comment]
I'm interested in your opinion of my latest commit with the three new sections for the `config.toml` file. Do you think that's ok, if the users **have** to add this to their config?
```toml
[tui]
[tui.sidebar]
[tui.mail_list]
```
?

**Comment by TornaxO7** [comment]
# Question
How should we let the user add his own keybindings?
I thought something like that:

```toml
[tui]
keybindings = {
    q = "quit"
}
```
Do you have a better idea?

**Comment by TornaxO7** [comment]
I was thinking to do it like vim:

```vim
<C-...> => Ctrl + ...
<A-...> => Alt + ...
<D-...> => command-key
```
But I don't know what this "command-key" or "super" key should be.

**Comment by TornaxO7** [comment]
# Question
I'm writing some tests currently and this functions fails:
```rust
#[test]
fn mbox() {
    let account = get_account("inbox@localhost");
    let mut imap_conn = ImapConnector::new(&account).unwrap();
    let names = imap_conn.list_mboxes().unwrap();
    let mboxes: Vec<String> = Mboxes::from(&names)
        .0
        .into_iter()
        .map(|mbox| mbox.name)
        .collect();
    assert_eq!(mboxes, vec![String::from("INBOX")]);
    imap_conn.logout();
}
```

What do I have to do to make it work? Is it normal that I don't have `INBOX` from this "account"?

**Comment by soywod** [comment]
> # Question
> Since I'll add a new part to the Config, should I split up the `src/config/model.rs` into it's different structs? Like
> 
> ```
> src/config/
>     account.rs
>     config.rs
>     tui.rs
> ```
> 
> ? What do you think about that? From my point of view, this makes it clearer, where to find what.

Sounds good to me!

> # Question
> In your `src/config/model.rs` you have this macro:
> 
> ```rust
>     #[serde(flatten)]
>     pub accounts: HashMap<String, Account>,
> ```
> 
> How does this work? I can't find it, if I search the term `flatten` in its [doc](https://docs.serde.rs/serde/index.html?search=flatten).

See https://serde.rs/attr-flatten.html. `Flatten` means that the struct will loose one level. In our case, it means that the key `accounts` is not present anymore: accounts are directly map to the parent struct (`Config`).

> I'm interested in your opinion of my latest commit with the three new sections for the `config.toml` file. Do you think that's ok, if the users **have** to add this to their config?
> 
> ```toml
> [tui]
> [tui.sidebar]
> [tui.mail_list]
> ```
> 
> ?

Hmmm I would prefer to find a way to make this _optional_. What prevents you to do so? Maybe [this](https://serde.rs/attr-default.html) could help you.

> # Question
> How should we let the user add his own keybindings?
> I thought something like that:
> 
> ```toml
> [tui]
> keybindings = {
>     q = "quit"
> }
> ```
> 
> Do you have a better idea?

Looks very good to me!

> I was thinking to do it like vim:
> 
> ```viml
> <C-...> => Ctrl + ...
> <A-...> => Alt + ...
> <D-...> => command-key
> ```
> 
> But I don't know what this "command-key" or "super" key should be.

Maybe we can take inspiration from [Emacs](https://www.gnu.org/software/emacs/manual/html_node/emacs/Modifier-Keys.html):

> Although only the Control and Meta modifier keys are commonly used, Emacs supports three other modifier keys. These are called Super, Hyper, and Alt.

See also http://ergoemacs.org/emacs/emacs_hyper_super_keys.html.



> # Question
> I'm writing some tests currently and this functions fails:
> 
> ```rust
> #[test]
> fn mbox() {
>     let account = get_account("inbox@localhost");
>     let mut imap_conn = ImapConnector::new(&account).unwrap();
>     let names = imap_conn.list_mboxes().unwrap();
>     let mboxes: Vec<String> = Mboxes::from(&names)
>         .0
>         .into_iter()
>         .map(|mbox| mbox.name)
>         .collect();
>     assert_eq!(mboxes, vec![String::from("INBOX")]);
>     imap_conn.logout();
> }
> ```
> 
> What do I have to do to make it work? Is it normal that I don't have `INBOX` from this "account"?

Integration tests need an IMAP server running in background to pass. It is sth I need to document, I did not take time to do so yet. I took inspiration from [imap-rust](https://github.com/jonhoo/rust-imap#running-the-test-suite). The simplest way is to start a GreenMail instance via docker:

```sh
docker run --rm -e GREENMAIL_OPTS='-Dgreenmail.setup.test.all -Dgreenmail.hostname=0.0.0.0 -Dgreenmail.auth.disabled -Dgreenmail.verbose' -p 3025:3025 -p 3110:3110 -p 3143:3143 -p 3465:3465 -p 3993:3993 -p 3995:3995 greenmail/standalone:1.6.2
```

**Comment by TornaxO7** [comment]
> Hmmm I would prefer to find a way to make this optional. What prevents you to do so?

Actually it's my lazyness :laughing: In my opinion it's more comfortable to implement the sections if you don't need to check if this sections have been set or not :laughing:

**Comment by TornaxO7** [comment]
> > I was thinking to do it like vim:
> 
> <C-...> => Ctrl + ...
> <A-...> => Alt + ...
> <D-...> => command-key
> But I don't know what this "command-key" or "super" key should be.
> 
> Maybe we can take inspiration from Emacs:
> 
> Although only the Control and Meta modifier keys are commonly used, Emacs supports three other modifier keys. These are called Super, Hyper, and Alt.
> 
> See also http://ergoemacs.org/emacs/emacs_hyper_super_keys.html.
> 

So you'd like to have it like in emacs? Am I right? Can you give me an example
how you imagine that?

**Comment by TornaxO7** [comment]
Another question: Have you planned to add a documentation to your code? Because it gets a little bit "hard" to look, if there's already a function which I need if I always have to go through their implementation.

**Comment by soywod** [comment]
> Have you planned to add a documentation to your code?

Yes, like tests. It is sth I plan to add over time. It's good you mention it, I will try to keep it it mind!

**Comment by TornaxO7** [comment]
# For everyone who is interested in
Each commit here should provide a runnable version of the TUI. If not, I'll mention it in the title of a commit. So everyone who is interested in how it is currently: You can try it out :D Keybindings are described in [this](https://github.com/soywod/himalaya/pull/155/commits/afb4e7188d30d1753cb191c659491effa083dc4e) commit.

**Comment by TornaxO7** [comment]
# Question
So... if you try the TUI out, you'll feel a ***big*** delay, when reading a mail... For me, this takes way too long time. So I was thinking of adding a config parameter like `offline` which will download the mails of a user to the given `download_dir` in order to have faster load times. What do you think? @soywod

**Comment by TornaxO7** [comment]
@soywod So.... I was looking through some [discussions](https://github.com/soywod/himalaya/discussions) and some other issues and so on and I've got the feeling that the majority doesn't [want]/[need] a TUI... so... what do you think about that (and everyone who is reading this)?

**Comment by TornaxO7** [comment]
Ok, I made up my mind: Even if only a few people are gonna use the TUI, I think it would be still a nice "little" feature for himalaya to have a TUI. :) (Thanks to my friends for motivating me back)

**Comment by TornaxO7** [comment]
> # Question
> So... if you try the TUI out, you'll feel a _**big**_ delay, when reading a mail... For me, this takes way too long time. So I was thinking of adding a config parameter like `offline` which will download the mails of a user to the given `download_dir` in order to have faster load times. What do you think? @soywod
> 
> # EDIT
> I just found [this](https://github.com/soywod/himalaya/wiki/Tips:offline-with-isync-dovecot) in your wiki. So this question is answered now.

Back to this question: Could we implement this feature as a "built-in" feature so the user just needs to set one line in the config instead of doing all of these steps? This would make it more user-friendly in my opinion.

**Comment by soywod** [comment]
> Ok, I made up my mind: Even if only a few people are gonna use the TUI, I think it would be still a nice "little" feature for himalaya to have a TUI. :) (Thanks to my friends for motivating me back)

If it can motivate you, the TUI was part of my plan. So I would have done it anyway. Because for me, the main purpose of Himalaya is to have a good API CLI so that UIs can be build on the top of it. And in my mind, it makes sense to propose a default UI of each (Vim, Neovim, Emacs, TUI, GUI etc). Maybe tomorrow, someone else will build a better UI that will become the standard, but at least Himalaya proposes a default one.

I really appreciate your initiative and your work, it would be too bad to give up now :smiley:

**Comment by soywod** [comment]
> Could we implement this feature as a "built-in" feature so the user just needs to set one line in the config instead of doing all of these steps?

Once Himalaya reaches a stable v1, I have 2/3 other side projects in mind related to this: 

- a CardDAV CLI to synchronize and query contacts (Himalaya could use it to auto-complete contacts when composing emails) (see #49 and https://github.com/soywod/cardamom)
- a IMAP synchronizer alla isync or IMAPOffline (this answers your question: it could be used as a feature like the TUI)
- and maybe a CalDAV CLI to synchronize and manage events and tasks

**Comment by soywod** [comment]
> You can try it out :D

I will try it out soon and let you know! (Can't wait to try :smiley:)

**Comment by TornaxO7** [comment]
> If it can motivate you, the TUI was part of my plan. So I would have done it anyway. Because for me, the main purpose of Himalaya is to have a good API CLI so that UIs can be build on the top of it. And in my mind, it makes sense to propose a default UI of each (Vim, Neovim, Emacs, TUI, GUI etc). Maybe tomorrow, someone else will build a better UI that will become the standard, but at least Himalaya proposes a default one.

> I really appreciate your initiative and your work, it would be too bad to give up now :smile: 

Yeet! I'll keep implementing this :) Thank you for your kind words!

**Comment by TornaxO7** [comment]
# Question
I have a few questions about the `src/msg/model.rs` file:
1. Are you gonna remove the `Tpl` structure since you added the `src/msg/tpl` directory with its own struct?
2. Will you split up the structs into independent files with their representive struct name? For example an `attachment.rs` for the struct `Attachment`.
3. Why do we have `ReadableMsg`, `Msg`, `MsgSpec` and `Msgs`? Wouldn't a single [`Mail`]/[`Msg`] struct do it with the appropriate functions?

**Comment by soywod** [comment]
> Are you gonna remove the `Tpl` structure since you added the `src/msg/tpl` directory with its own struct?

Yes, I just forgot to clean some part.

> Will you split up the structs into independent files with their representive struct name? For example an `attachment.rs` for the struct `Attachment`.

Let's say I try to split by "business" (msg, attachment, mbox etc) rather than type (struct, trait etc).

> Why do we have `ReadableMsg`, `Msg`, `MsgSpec` and `Msgs`?

- `Msg` is the main type
- `Msgs` is a wrapper around `Vec<Msg>`. The main idea behind is to be able to implement [`From<imap::Fetch>`](https://github.com/soywod/himalaya/blob/0d7b490f98cb7626c478349bd61e2edd3fa76229/src/msg/model.rs#L636-L640) and [`Display`](https://github.com/soywod/himalaya/blob/0d7b490f98cb7626c478349bd61e2edd3fa76229/src/msg/model.rs#L648-L652) (for the table).
- `ReadableMsg` is another representation of a message that is used for the command `read`. I put this in a struct to benefit the `derive(Serialize)` from serde (JSON output).
- `MsgSpec` was used before the template refactor, I need to remove it

I think some refactor + code documentation is needed, I will take care of it and let you know.

**Comment by TornaxO7** [comment]
# Question
I'll try to implement the multi-accounts now, so all accounts are listed in a tab-bar where you can "scoll" through them with `gt` (like in vim with tabs). My idea would be to store each "state" of the accounts.

# Example
Suppose we have these accounts:

```
Account A
Account B
```

And suppose we're currently on account A, writing a mail. Suddenly we got the notification that account B received a new mail. Now the user can switch to account B and read his new mail, after that he/she switches back to account A and gets it's old status restored, like the entrys of the header and all attachments which have been filled/added.

Do you agree to that?

**Comment by TornaxO7** [comment]
# Question
So in the documentation of tui-rs, they're saying [here](https://docs.rs/tui/0.15.0/tui/widgets/index.html), that the functions should be used as commands and not be stored. But this leads to some "high" CPU usage (at least on my machine). So I'd like to store them, at least a part of the stuff. What do you think about it? Is it fine for you if I do that?

**Comment by soywod** [comment]
> And suppose we're currently on account A, writing a mail. Suddenly we got the notification that account B received a new mail. Now the user can switch to account B and read his new mail, after that he/she switches back to account A and gets it's old status restored, like the entrys of the header and all attachments which have been filled/added.

Looks great! I also see accounts as independent views/panels.

> Thank you so much for being so responsive! :)

You already spend a lot of time on this feature, the minimum I can do is to be reactive :wink: 

> So in the documentation of tui-rs, they're saying [here](https://docs.rs/tui/0.15.0/tui/widgets/index.html), that the functions should be used as commands and not be stored.

I'm not sure what they mean by _storing_. The high CPU usage appears when? Always? Or when doing an action?

**Comment by TornaxO7** [comment]
> I'm not sure what they mean by storing. The high CPU usage appears when? Always? Or when doing an action?

I mean storing the widgets. Like the [paragraph widget](https://docs.rs/tui/0.15.0/tui/widgets/struct.Paragraph.html). Otherwise we'd have to create each widget for each event (key press).

**Comment by soywod** [comment]
I see. Well, I do not know enough to give an opinion, but sounds OK for me to store them. Let's go for it!

**Comment by TornaxO7** [comment]
My holidays ended now and school is taking some time but I'll look to be able to invest some time into the TUI! (Just to let you know if the case happens, that I couldn't/can't push some new stuff).

**Comment by soywod** [comment]
Don't worry, this task is clearly not a priority. Come back on it whenever you can. And even if you don't, I will take it back. Thank you anyway for what you provided so far :wink:

**Comment by TornaxO7** [comment]
On the wiki page about the config file, you added this:

```toml
global-settings

[account-name-1]:
account-specific-settings

[account-name-2]:
account-specific-settings
```
What is the difference between the name between the `[...]` brackets and the sub-value `name` like this:
```toml
[account1]
name = "What's with this name?"
```

**Comment by soywod** [comment]
> What is the difference between the name between the `[...]` brackets and the sub-value `name` like this:
> 
> ```toml
> [account1]
> name = "What's with this name?"
> ```

It is your full name. For eg, if you put `name = "Paul DURANT"` then this name will be used in the `From` header when you compose a message. See https://github.com/soywod/himalaya/wiki/Configuration:config-file#global-settings.

**Comment by TornaxO7** [comment]
So currently I'm working on the viewer-mode (the mode, when you're reading your mail). I need to get the header information for that and the attachments. You said, that you're refactoring, right? What do you think about, creating a struct, which represents a whole mail? For example the function `ImapConnector.read_msg` should return a struct, which includes all information of the mail: The headers, the body and so on. What do you think of that?

**Comment by soywod** [comment]
I did not refactored this part yet. But a single struct sounds good to me!

**Comment by TornaxO7** [comment]
Do you want to refactor it or should I do it?

**Comment by TornaxO7** [comment]
Do you mean with "propose" that I can create another pull request or a propose as a text what we could add/change?

**Comment by TornaxO7** [comment]
What do you think about storing all mail-relavant values extra on the heap? So what I mean with that is for example converting the [Flag::Cow<'a, str](https://docs.rs/imap/2.4.1/imap/types/enum.Flag.html) into a `String` or in other words:
Converting all attributes of the Mail into a heap-value like `Vec` or `String`. This would make it easier (for us) to access the values since we can be sure that they will exist as long himalaya runs + we can use references on them afterwards without any problems.

**Comment by TornaxO7** [comment]
Ok, so I started to implement the rough structure of a mail. It's implementation is [here](https://github.com/TornaxO7/himalaya/blob/refactor/src/msg/mail.rs) in my `refactor` branch. You can also clone my repo, switch to the `refactor` branch and build the doc (or just read the doc-strings from the code). What do you think about that?

**Comment by TornaxO7** [comment]
Hey... I just want to let you know that I **don't** want to force you to accept my suggestion. I feel a little bit "bad" to say "let's refactor src/msg/model.rs`" (especially after reading [this](https://www.redox-os.org/news/open-source-mental-health/) article) because you invested pretty much time in himalaya and I don't want to "wipe all" of your work, just to interact with the data easier for the TUI... if you feel "attacked" or something like that due to my suggestion above, feel free to tell it to me! :)

**Comment by soywod** [comment]
Don't worry, all is fine :) I just don't have time for myself these days (I'm preparing a moving). I'm really open to discussion. Feel free to propose (post or PR), I may just be slow to answer!

**Comment by TornaxO7** [comment]
Alright! Take your time for you moving :)

I think that I'll do it as follows: I'll use the "new" struct for the TUI for the time being. Than you can take a look at it and we'll see further if you want to keep it or not. What do you think about that?

**Comment by soywod** [comment]
Sound great :)

**Comment by TornaxO7** [comment]
Ok, so I've got a little problem here and I'd like to hear your opinion. 

# Problem description
Your API is mainly based on "short-living-connections". That means that allmost
all of your msg-functions need to create an imap-connection in their
function-body. For example, if the user wants to read a mail, your function
`src/msg/model.rs -> msg_matches_read()` creates a new imap connection to the
server, does it works and closes the connection then.

The problem for ["me"]/[the TUI] is gonna be a little bit slow, since I always
have to fetch the information from the server for each TUI-Mode:
 - The normal mode: Where you can see the mailboxes and the mails => Fetch the
 mailbox names from the server + the data from the server with
 `ImapConnector::list_mboxes()` and `ImapConnector:list_msgs()`
 - The view mode: Load the content, header and the attachments of the mail =>
 `ImapConnector:read_msg()` and if you go back to the listing, I'd have to fetch
 all information again from the server for the normal mode.
 
So for better performance I was thinking of loading all mails at once and really
everything: All information of the mails and mailboxes, that's why I wanted to
create this Mail-struct as I described it in my previous messages.

# Solutions / Ideas
## Always fetching
One "solution" would be to fetch the datas everytime when we need to. For
example that means that the TUI is fetching the content of a mail, only if it's
needed (in other words: When the user enters the viewing-mode).

### Pros
- Easy to implement
- Almost nothing to change in the current api

### Cons
- Long loading time, since we have to interact with the server pretty often
(people with a slow internet would have to wait even longer...)

## Holding connection
I could create the imap connection for each account and store this connection
(created with `ImapConnector::new()`) as a variable for each account, so I can
"store" the returned values of the current Himalaya-API, like the output of
`src/imap/model.rs -> ImapConnector::list_mboxes()` due to the
`imap::types::ZeroCopy` which forbidds me to store the returned value in another
variable, *at least if the connection is closed afterwards*.

### Pros
- Only some small or even none changes are needed on the Himalaya API since I
can store the returned values fromthe `ImapConnector` then

### Cons
- TUI needs to keep connection to the Imap-Server(s) until the TUI is gonna be
closed even if we don't have to interact with the server. I don't know if it's
ok for the server to do that. The worst case would be, that the server closes
the connection due to inactivity, which means that the TUI has to "shut down" as
well.

## Storing the data/Caching
Here we are fetching all information only one time, which means that all
information of the mailboxes and mails will be fetched from the server and they
will be stored for example in a struct (as I did above).

### Pros
- Needs only one time to load the data => Afterwards the user can do everything
instantly since the data is stored in memory

### Cons
- Huge changes in the Himalaya API (new struct for example to store all that
        data)
- One big loading time in the beginning even if the user just wants to read one
mail


# Extra information
As you have seen in my previous comments I was thinking more about using the
third option: Storing the data/Caching. The reason is, that I liked the speed in
neomutt. I just needed to open it and I could start doing my stuff without any
delay while a cronjob is interacting in the background with the server in a
period of time. That's what I like in the third option. But as I wrote down in
the cons-section of it: Its implementation is gonna be more complicated than the
others. What do you think about it? Which way would you like to chose?

**Comment by GreatGodOfFire** [comment]
I would cache 50 emails for every account and add the possibility to load more. After loading 50 mails you can disconnect and open a new connection when you need to load more or when an email has been opened.

**Comment by TornaxO7** [comment]
@soywod Did you plan to implement [this](https://github.com/soywod/himalaya/wiki/Tips:offline-with-isync-dovecot) so the users don't need to do all of these steps?

**Comment by TornaxO7** [comment]
@soywod what do you think about using a sql  database like sqlite to store the mails?

**Comment by TornaxO7** [comment]
Ok, nevermind first. My friends clearlified me that I should focus on the TUI first not on other stuff in parallel. So forget my two previous posts.

**Comment by TornaxO7** [comment]
Hi! You are using this:
```rust
        use lettre::message::{
            header::*,
            {Body, Message, MultiPart, SinglePart},
        };
```
in the `to_sendable_msg` function of `src/msg/model.rs`. Where can I read more about it? I tried to look up the [Message::builder()](https://docs.rs/lettre/0.9.6/lettre/enum.Message.html?search=builder) function for example but I can't find anything to it.

**Comment by TornaxO7** [comment]
Ok, I just found out, that I was looking at the latest stable release of `lettre` and not on `0.10.0-rc.1`. Of curiosity: Why don't you want to use a stable version?

**Comment by soywod** [comment]
> Ok, so I've got a little problem here and I'd like to hear your opinion.
> [...]

This is _indeed_ a real problem, but it is not _new_ (I have it in mind since the beginning of Himalaya). My conclusion is that caching is a complex problem. We can't just cache items: what if an item is modified outside of Himalaya? How to deal with conflicts? When/how to invalidate the cache?
I came up to the conclusion that this job should be done outside of Himalaya: to have a kind of IMAP synchronizer that will take care of it in background, and Himalaya should use this cache instead. Such tools already exist ([isync](https://isync.sourceforge.io/), [OfflineIMAP](http://www.offlineimap.org/)) and they are doing the job quite well. This is what I personally do and performance are really good since Himalaya connects to a local IMAP server instead of a remote one. I wrote a [wiki post](https://github.com/soywod/himalaya/wiki/Tips:offline-with-isync-dovecot) about how to set up such a configuration.

But I agree that _this is not optimal_. The user experience is not so good, since you need to configure stuff to increase perf. The best would be to have a synchronizer packed with Himalaya.

So my conclusion is to implement a CLI IMAP synchronizer (in a new project) that can also be used as a lib to access cached items directly from the code. I also see this lib as a feature that should be enabled (like the TUI). But for sure, this work should not be included in the TUI. It is sth to take care when all the rest is stable enough.

I also plan to do the same with _contact completion_ (see #49). See also https://github.com/soywod/himalaya/discussions/118#discussion-3331172.

I hope it answers more or less your question.

**Comment by soywod** [comment]
> Of curiosity: Why don't you want to use a stable version?

I think it was for the better API regarding messages and attachments builders.

**Comment by TornaxO7** [comment]
@soywod ok, but would you still agree, if I "refactor" the `Msg` structure to use only *one* structure to create a mail? Instead of `Msg` and `Tpl`? I'm thinking of a structure like this one:
```rust
#[derive(Debug)]
pub struct Mail<'mail> {

    /// All added attachments are listed in this vector.
    pub attachments: Vec<Attachment>,

    /// The flags for this mail.
    pub flags: Vec<Flag<'mail>>,

    /// All information of the envelope (sender, from, to and so on)
    pub envelope: Envelope,

    /// The parsed content of the mail which shoud make it easier to access
    pub parsed: Option<ParsedMail<'mail>>,
}

pub struct Envelope {
    pub date: String,
    pub subject: String,
    pub from: Vec<String>,
    pub sender: Vec<String>,
    pub reply_to: Vec<String>,
    pub to: Vec<String>,
    pub cc: Vec<String>,
    pub bcc: Vec<String>,
    pub in_reply_to: String,
    pub message_id: u32,
}

pub struct Attachment {
    pub filename: String,
    pub body_raw: Vec<u8>,
}
```

(Of course these will be implemented in another pull request)

**Comment by soywod** [comment]
Yes it sounds good to me and it makes sense, except for the `Mail` name (I would keep `Msg` since I use it everywhere, also in the vim plugin).

**Comment by TornaxO7** [comment]
# Information
For everyone who's waiting for more updates on this PR. This PR is stopped at the moment. Because the TUI needs some "features" which are implemented in the [other PR](https://github.com/soywod/himalaya/pull/173). So don't worry. This PR **isn't given up**.

**Comment by TornaxO7** [comment]
# Update
The Refactor PR has been merged but I think that fixing some other issues first, before continue the TUI might be better. Because otherwise I think I'd need to refactor more and more, if more important code changes, like the error handling. Shouldn't take too long (hopefully). @soywod is that fine for you?

**Comment by TornaxO7** [comment]
PS: It's pretty nice to see that many other people are looking at this PR as well :) Thank you for visiting this PR! c(^-^)c

**Comment by soywod** [comment]
> @soywod is that fine for you?

Yes it sounds great. Now that your PR on msg refactoring is merged, I will take time to test deeply everything, fix major bugs and clean the codebase (also update the error management).

**Comment by TornaxO7** [comment]
Wouldn't it make more sense to write more tests instead of testing it manually everytime? That would save you some time I guess ;)

**Comment by TornaxO7** [comment]
Alright, I'll leave the error handling to you then and look for another issue.

**Comment by soywod** [comment]
> Wouldn't it make more sense to write more tests instead of testing it manually everytime? That would save you some time I guess ;)

Of course, but we need time to write them! Tests will come over time. I hope one day we will not need to test manually :wink:

**Comment by DhruvaSambrani** [comment]
@TornaxO7 How do I try out the tui?

**Comment by TornaxO7** [comment]
@DhruvaSambrani Sorry for the very late reply! Generally, you can try it out by cloneing my fork and compile it on your own and run it (`cd <path to my fork> && cargo run tui`) but this fork is pretty much outdated compared to the source code of himalaya at the moment.....

**Comment by soywod** [comment]
I have more free times the days, I will try to fix conflicts and maybe finish what you started!

**Comment by soywod** [comment]
I have more free times the days, I will try to fix conflicts and maybe finish what you started!

**Comment by soywod** [comment]
@TornaxO7 do you mind if I recreate a branch for the TUI (starting from `development` on my repo) and integrate piece by piece what you already done? I tried to merge `development` into your branch but the code base changed so much, it just does not fit any more. Especially the backend part: your branch is still tied up to the old `ImapConnector`.

**Comment by TornaxO7** [comment]
Wait, you're thinking that the backend is already ready for the TUI?

**Comment by TornaxO7** [comment]
Don't worry, I think that I'll have to start from the biginning anyhow, since the code changed that much. We can even close this PR at the moment.

**Comment by soywod** [comment]
> Wait, you're thinking that the backend is already ready for the TUI?

Implementations may (will) need some adjustments but the trait is solid enough to be used.

> Don't worry, I think that I'll have to start from the biginning anyhow, since the code changed that much. We can even close this PR at the moment.

I also think it's gonna be easier this way. But I thought you were not so available, that's why I started to take back this feature. Do you feel like doing it? Anyway, I already pushed sth on the `tui` branch. All the args and handlers system is set up and plugged to the `main.rs`. Now, the work left is to integrate all what you wrote so far, and change the `ImapConnector` by `Box<&mut Backend>`.

**Comment by TornaxO7** [comment]
> Implementations may (will) need some adjustments but the trait is solid enough to be used.

I'd still wait for some features. Especially for the caching! Because during the time, when I was still doing this, the fetching time was horrible. Everytime when you want to look the content of your mail, you'd have to wait about a second to be able to read it.

> I also think it's gonna be easier this way. 

Then you can close it you want or I'll do it tomorrow.

> But I thought you were not so available, that's why I started to take back this feature.

What do you mean with this?

> Do you feel like doing it? 

Not yet, I'm in the exam-session at the moment. Tomorrow is my first one (one of 3 if you exclude programming) yaaaaaaaay ._. Also I need some to do the wizard first.

> Now, the work left is to integrate all what you wrote so far, and change the ImapConnector by Box<&mut Backend>.

Hm... I think that restarting won't hurt that much and as far as I remember correctly, I didn't do that much, otherwise I can look a little bit back to the old code and adjust it.

**Comment by soywod** [comment]
> I'd still wait for some features. Especially for the caching!

I will not implement a cache system for those (well thought) reasons:

- Himalaya is not an offline solution to read your emails. It is just a command line interface over your emails, using different backends. The IMAP backend relies on the network, so it is normal to have some delay.
- A cache system does not make sense on a CLI. When you run `himalaya list` you always want to have an up to date list, you never have a chance to use your cache.
- If you are looking for offline, you need to synchronize your emails locally in a Maildir (see mbysnc and offlineimap). Since Himalaya supports the Maildir format, you can interact directly with it instead of your IMAP server.

That said, the TUI has different requirements. To have the best UX (in my opinion), a TUI should work offline (a bit like a GUI, think Thunderbird), and it should work out of the box (or with toggle feature). This last statement is not compatible with asking users to install and configure on their own mbsync or offlineimap. And none of them propose a lib. The only solution I see for now is to develop a Rust lib (and a CLI?) that synchronizes remote IMAP/POP server with a local Maildir. This way the Himalaya's TUI could rely on it to offer offline to its users!

> What do you mean with this?

I just refer to what you said in the TUI issue https://github.com/soywod/himalaya/issues/24#issuecomment-985506111:

> If anyone has more time and motivation (I don't mean it in a bad way) than me, then you can create your own fork and implement the TUI because at the moment I'm pretty much exhausted by my university and I'd like to complete my eduacational project first... and... sadly the code in my fork isn't up to date anymore...

**Comment by TornaxO7** [comment]
>  I will not implement a cache system for those (well thought) reasons: (...)

Hm... I understand your arguments. Welp, it sounds reasonable to avoid making himalaya a cli-tool "frontend" with *a lot* of backend (like downloading mails) stuff.

>  To have the best UX (in my opinion), a TUI should work offline (a bit like a GUI, think Thunderbird), and it should work out of the box (or with toggle feature). 

Yeah, I agree here.

> And none of them propose a lib. The only solution I see for now is to develop a Rust lib (and a CLI?) that synchronizes remote IMAP/POP servers with a local Maildir. This way the Himalaya's TUI could rely on it and offer offline to its users!

Pew, that's not gonna be a "little" project I guess...

Anyway, I'm agreeing here to only provide the TUI as "another" frontend for himalaya.

But before starting to implement the TUI, I'd like to collect some ideas first, how it should look like and what functionalities it should provide. This would help me to structure it and avoids reimplementing stuff.

**Comment by soywod** [comment]
> Pew, that's not gonna be a "little" project I guess...

Well, in fact I will reuse many parts from Himalaya, it should not be that long! Here the repo https://github.com/soywod/everest.

> But before starting to implement the TUI, I'd like to collect some ideas first, how it should look like and what functionalities it should provide. This would help me to structure it and avoids reimplementing stuff.

It is a good idea! A good start would be to test the vim and/or the emacs plugin. I could also try to list a bit the common features that a frontend should implement.

**Comment by TornaxO7** [comment]
> I could also try to list a bit the common features that a frontend should implement.

Aye! Something like this would be helpful! I created a [discussion](https://github.com/soywod/himalaya/discussions/332) for this, since I think that it suits here for our needs(?).

**Pull request closed without merging**
