### PR TITLE
bumping lettre to 0.10.0-rc.7

### PR DESCRIPTION
**Pull request by TornaxO7**

### CODE REVIEW

**Review by soywod — CHANGES_REQUESTED** [review]
Did you run `cargo build`? It looks like the lock file did not update.

**Comment by TornaxO7** [comment]
Whoops, I forgot to do that

**Comment by soywod** [comment]
It could be the reason of the failed nix build btw

**Comment by soywod** [comment]
It could be the reason of the failed nix build btw

**Comment by soywod** [comment]
This time, the nix build is OK but not the tests :rofl: could your merge `origin/development` and push to see?

**Comment by TornaxO7** [comment]
Oh no, I'm getting some errors in the `cli` module.

**Review by soywod — APPROVED** [review]

**Comment by TornaxO7** [comment]
What the o.O

**Comment by TornaxO7** [comment]
I'm very irrated now because it looks like that `Envelopes` used to be a trait but now it's a struct?

**Comment by TornaxO7** [comment]
I'm getting the same error if I switch to the development branch and do

```zsh
cargo test --all-features --all
```

**Comment by soywod** [comment]
Tests are broken on `development` since my last commit, my bad! I'm fixing it, I let you know when you can pull again.

> I'm very irrated now because it looks like that `Envelopes` used to be a trait but now it's a struct?

It is because of #340, the backend trait had this member:

```rust
fn get_envelopes(&mut self, mbox: &str, page_size: usize, page: usize) -> Result<Box<dyn Envelopes>>;
```

But `Envelopes` expected the trait `Printable`:

```rust
pub trait Envelopes: fmt::Debug + erased_serde::Serialize + PrintTable + any::Any;
```

which is a big problem: the `Printable` trait is used to print tables, this should belong to the `cli` module and not the `lib`. So I started to replace `Envelopes` and `Mboxes` traits by structs. I do not know if my explanations were clear enough, but to summarize it was a necessary step to move the `Backend` trait to the `lib` module.

**Comment by soywod** [comment]
I just fixed tests on `development`, you can pull again then we can merge this PR.

**Comment by TornaxO7** [comment]
Done! The tests should pass now (`cargo test --all-features --all` run succesfully on my machine!)

**Comment by TornaxO7** [comment]
Yay!

**Pull request merged**
