### PR TITLE
292 cannot build sendable message missing destination address invalid envelope

### PR DESCRIPTION
**Pull request by TornaxO7**
TL;DR:
    - Just adjusted the version of lettre :D

should fix https://github.com/soywod/himalaya/issues/292

### CODE REVIEW

**Comment by TornaxO7** [comment]
Eeeeh, welp, somehow `notmuch` isn't installed on the Nix system for the nix-build?

**Comment by soywod** [comment]
> Eeeeh, welp, somehow `notmuch` isn't installed on the Nix system for the nix-build but I don't know how to do it o.O

It's fine, I will fix this in another commit. Thank you for the PR :pray:

**Comment by paolobarbolini** [comment]
FYI rc7 came out a few hours after this PR. You might want to update this now as we soon expect to make the final 0.10.0 release.

Also I'm following a few of the issues that have been coming up lately and I'll try to see if there's something I can help with, as the latest releases tried making the encoder more stricter and correct to the RFC.

**Comment by TornaxO7** [comment]
Alright, I'll create the PR tomorrow

**Pull request merged**
