### PR TITLE
himalaya-vim nix package

### LINKED ISSUE #139: Upstream the Vim plugin to nixpkgs
I would expect one of three things here:

1. Ideally, it's just there in `pkgs.vimPlugins.himalaya` or `pkgs.vimPlugins.himalaya-vim`.

2. The there's something in the Flake that exposes the Vim plugin (as an app or package?)

3. Or it's bundled with the main package and it could be added if needed:

```nix
# custom plugins
{
  himalaya = vimUtils.buildVimPluginFrom2Nix {
    pname = "himalaya";
    version = "VERSION";
    src = "${pkgs.himalaya}/share/vim"; # or some better location
  };
}
```

```console
$ tree (nix-build --no-out-link '<nixpkgs>' -A pass)                       
/nix/store/yn90aa8viibbh439pxqnli5387yfn9ma-password-store-1.7.3
├── bin
│   ├── pass
│   └── passmenu
├── lib
│   └── password-store
│       └── extensions
└── share
    ├── bash-completion
    │   └── completions
    │       └── pass
    ├── emacs
    │   └── site-lisp
    │       └── password-store.el
    ├── fish
    │   └── vendor_completions.d
    │       └── pass.fish
    ├── man
    │   └── man1
    │       └── pass.1.gz
    └── zsh
        └── site-functions
            └── _pass

15 directories, 7 files
$ tree (nix-build --no-out-link '<nixpkgs>' -A himalaya)                   
/nix/store/sdfmnqaarc5ighhlahfbxkmd6bcl42yl-himalaya-0.3.0
├── bin
│   └── himalaya
└── share
    ├── bash-completion
    │   └── completions
    │       └── himalaya.bash
    ├── fish
    │   └── vendor_completions.d
    │       └── himalaya.fish
    └── zsh
        └── site-functions
            └── _himalaya

8 directories, 4 files
```

Here we can see that `pass` offers `emacs` stuff in `share/'. I'm a Nix newb and I'm having trouble figuring out the best way to pull this into my own config.

### PR DESCRIPTION
**Pull request by toastal**
outdated comment from putting the plugin inside the main derivation

### CODE REVIEW

**Comment by toastal** [comment]
```console
$ nix build .#himalaya-vim
$ tree result/
result
└── share
    └── vim-plugins
        └── himalaya-vim
            ├── autoload
            │   └── himalaya
            │       ├── mbox.vim
            │       ├── msg.vim
            │       └── shared
            │           ├── bindings.vim
            │           ├── cli.vim
            │           ├── log.vim
            │           ├── thread.vim
            │           └── utils.vim
            ├── doc
            │   ├── himalaya.txt
            │   └── tags
            ├── ftplugin
            │   ├── himalaya-msg-list.vim
            │   ├── himalaya-msg-read.vim
            │   └── himalaya-msg-write.vim
            ├── lua
            │   └── himalaya
            │       └── mbox.lua
            ├── plugin
            │   └── himalaya.vim
            ├── README.md
            └── syntax
                └── himalaya-msg-list.vim

12 directories, 16 files
```

**Comment by soywod** [comment]
Thanks for your help! The problem is I don't know enough about Nix. It could be great if someone else could have a look?

**Comment by toastal** [comment]
:100: I need it double-checked just as much

**Comment by soywod** [comment]
@srid?

**Comment by srid** [comment]
It looks generally good to me, and here are my thoughts:

- @toastal You might want to undo those indentation changes, to make the diff small
- Does the [CI](https://github.com/soywod/himalaya/blob/master/.github/workflows/nix-build.yaml) pass for this PR? I think it requires @soywod's approval to run. 
- @toastal How should Nix users use this plugin? Is there a documentation on it somewhere? Perhaps it can be added to the wiki [here](https://github.com/soywod/himalaya/wiki/Installation:using-nix)

If the CI runs, that should be good to merge.

**Comment by toastal** [comment]
Removed _most_ of the indentation. I think the `let` being indented 1 must be an issue. I think an [EditorConfig](https://editorconfig.org/) would have cleaned up the trailing whitespace issues as generally projects prefer them remove. (:thinking: perhaps @soywod would like to add this config file?)

I'm not sure if there's a test or not. I had some issues trying to get the plugin upstreamed do to the `executable("himalaya")` Vim line where `himalaya` was not on the `PATH` for the configuration step used by the Vim plugin building tools. If I understood how to import a flake in `nixpkgs` (or I use flakes instead of legacy for my NixOS config), I would just reference this flake.

**Comment by toastal** [comment]
This seems to be _good enough_. I got the Vim plugin merged upstream for non-flake. If it's okay with everyone, I think it's mergable.

**Comment by soywod** [comment]
Thank you :tada:

**Pull request merged**
